language: ruby
cache: bundler
script: 'bundle exec rake'
rvm:
  - 2.5.1
services:
  - mongodb

notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
    on_failure: change
    on_success: never

matrix:
  include:
    - rvm: 2.5.1
      env: MONGOID_VERSION=7
